### ISSUE TITLE
Citra core fails to compile: LoadStateBuffer and SaveStateBuffer

### ISSUE THREAD

**Issue by Shoegzer** [libretro/citra#105]
As noted, attempting to compile the citra core results in an error:
```
/home/testing/Desktop/retroarch/libretro-super/libretro-citra/src/citra_libretro/citra_libretro.cpp: In function 'size_t retro_serialize_size()':
/home/testing/Desktop/retroarch/libretro-super/libretro-citra/src/citra_libretro/citra_libretro.cpp:656:49: error: 'class Core::System' has no member named 'SaveStateBuffer'
  656 |         savestate = Core::System::GetInstance().SaveStateBuffer();
      |                                                 ^~~~~~~~~~~~~~~
/home/testing/Desktop/retroarch/libretro-super/libretro-citra/src/citra_libretro/citra_libretro.cpp: In function 'bool retro_unserialize(const void*, size_t)':
/home/testing/Desktop/retroarch/libretro-super/libretro-citra/src/citra_libretro/citra_libretro.cpp:678:44: error: 'class Core::System' has no member named 'LoadStateBuffer'
  678 |         return Core::System::GetInstance().LoadStateBuffer(buffer);
```
Information:
* OS: Linux Mint 20.3 / kernel 5.13
* Compiler: gcc-10 (citra core doesn't compile with gcc-11)
* CPU: Intel i7-10870H
* Bad commit: 44e01f99016008eff18bc7a28234d1098382358d
* Last known good commit:  7fa64af3d628adf7b2825b89a3cdc8be7f731d0a
* Compile log: [here](https://controlc.com/17575fe6)

This issue seems to stem from 5d881638ad13476981189d9b31c3a5d69d11e8fe.  @m4tsa Any thoughts you have here are welcome.

**Comment by m4tsa** [comment]
You need to build using the makefile instead of using cmake.

**Comment by Shoegzer** [comment]
Thanks.  The [buildbot linux recipe](https://github.com/libretro/libretro-super/blob/master/recipes/linux/cores-linux-x64-generic) currently uses cmake:

`citra libretro-citra https://github.com/libretro/citra.git master YES CMAKE Makefile build -DENABLE_LIBRETRO=1 -DLIBRETRO_STATIC=1 -DENABLE_SDL2=0 -DENABLE_QT=0 -DCMAKE_BUILD_TYPE="Release" -DENABLE_WEB_SERVICE=0`

This was working until at least 7fa64af3d628adf7b2825b89a3cdc8be7f731d0a.  In light of your comment, I assume the recipe should be changed, I'm guessing to something like:

`citra libretro-citra https://github.com/libretro/citra.git master YES GENERIC Makefile`

...but this would not capture the effect of the six cmake flags above.  Any way to preserve them easily in the buildbot recipe?

**Comment by abouvier** [comment]
The recipes are not used anymore, you should look at the [.gitlab-ci.yml](https://github.com/libretro/citra/blob/master/.gitlab-ci.yml) file at the root of each repo.

**Comment by Shoegzer** [comment]
They are though.  From your link:

> Libretro-super...can still be useful for the regular user to build stuff for personal use, and we will continue to update it. But it is no longer a fundamental part of our infrastructure like before, more a user convenience tool for building cores.

They are indeed quite useful and convenient, I use them exclusively because they suit an internal build process and I've been maintaining them with occasional updates for myself and others.

**Comment by Shoegzer** [comment]
Closing this.  PCSX2 core now compiles with libretro-super after my [PR](https://github.com/libretro/libretro-super/pull/1644) was merged.
